#Logging level config
logging :
  level:
   org:
    edupoll: debug
   
 #Spring config  
spring:
 mustache:
   servlet:
     expose-session-attributes: true
     
 jackson:
   default-property-inclusion: NON_NULL    
     
 datasource :
      driver-class-name : oracle.jdbc.driver.OracleDriver
      url : jdbc:oracle:thin:@3.34.136.30:1521:xe   
      username : moim
      password : 1q2w3e4r
 mvc :
   format : 
     date : yyy-MM-dd
 jpa :
  show-sql: true    
      
      
      
      

server :
  servlet :
    encoding :
      force : true         